### ISSUE TITLE
give example of loading dataset and models without using using dataset_container / load_dataset() 

### ISSUE THREAD

**Issue by cmacdonald** [hpclab/rankeval#24]

**Comment by strani** [comment]
I added in the notebook related to the [https://github.com/hpclab/rankeval/blob/master/notebooks/Dataset%20Utilities.ipynb](Dataset%20Utilities) two examples of how to load a Dataset from file and from numpy array.

Regarding models, the notebooks are plenty of examples on how to load a model from file: e.g.,:
`model = RTEnsemble(path_model_file, name="XXX", format="QuickRank")`

The formats currently supported are: QuickRank, ScikitLearn, XGBoost, LightGBM, CatBoost and Jforests.
