### ISSUE TITLE
supporting (gzip) compressed svmlight formatted files?

### ISSUE THREAD

**Issue by cmacdonald** [hpclab/rankeval#26]
please.

Perhaps this SO comment has the solution:
https://stackoverflow.com/a/7841686/9989050

Craig

**Comment by strani** [comment]
I will give it a look tomorrow but any solution has to avoid adding an external dependency which is out of the control of pypi. This is the biggest challenge I see now.

**Comment by cmacdonald** [comment]
OK - can you parse from a python filehandle stream thing instead?

**Comment by strani** [comment]
I implemented the first solution of this feature. You can find it in the branch `dataset-reader-stream`. It automatically opens a gzip o bzip file correctly but supports also file descriptors in place of file-path (for additional and personalized usage). The first tests were ok.

If you would like to give a chance to that code, you are welcome.
The solution implemented is all but clean, but it works!

**Comment by strani** [comment]
I implemented also support to dump compressed dataset, similarly to the load. Everything is on the master right now. Issue closed.

**Comment by cmacdonald** [comment]
@strani  thanks very much!
