### ISSUE TITLE
inaccurate description/reasoning in LIght

### ISSUE THREAD

**Issue by zenogantner** [hpclab/rankeval#5]
http://rankeval.isti.cnr.it/docs/rankeval.model.html
under rankeval.model.proxy_LightGBM module:

> ... This is required because LtR datasets do not have missing values, but have feature values equals to zero (while LightGBM consider zero valued feature as missing values). ...

I do not think this is correct.

[This is what the LightGBM documentation says:](https://github.com/Microsoft/LightGBM/blob/master/docs/Advanced-Topics.rst)

> LightGBM enables the missing value handle by default. Disable it by setting use_missing=false.
> LightGBM uses NA (NaN) to represent missing values by default. Change it to use zero by setting zero_as_missing=true.
> When zero_as_missing=false (default), the unshown values in sparse matrices (and LightSVM) are treated as zeros.

**Comment by strani** [comment]
You are right, I'm not sure if something changed in the middle. 
I fixed the documentation on the source file, now it's on the develop branch.
Soon I will update also the docs on the official website.

Thank you for  helping us improving rankeval 👍
