### ISSUE TITLE
dataset.clear_X(): What is it used for?

### ISSUE THREAD

**Issue by zenogantner** [hpclab/rankeval#9]
Is this method really needed/worth keeping?

It is not used within the code base.
dataset.X = None should be sufficient if one really wants to save memory under specific circumstances, and should leave X for garbage collection (if there are no other references to it).

del self.X modifies something that was passed into the object.
Not sure whether this is really something that you want to do...

**Comment by strani** [comment]
You are right, I removed the `clear_X` method in the develop branch.
